### ISSUE TITLE
Is this still working/maintained?

### ISSUE THREAD

**Issue by ChristopherJohnson25** [redaxmedia/sendgrid-proxy#2]
Trying to figure out how to get this work. I deployed the proxy via heroku and am still getting the no cors error. Are there any specific steps I may be missing? This is a lifesaver if it works! 

Thank You.

**Comment by ChristopherJohnson25** [comment]
Thanks for responding to this! Apologies for the delay....I'm still getting a 404 when navigating to the page and when going to the api_keys url I'm getting 

`{"errors":[{"field":null,"message":"access forbidden"}]}`

Any ideas? Thanks!

**Comment by redaxmedia** [comment]
Problem between keyboard and chair... your credentials are just invalid...

**Comment by ChristopherJohnson25** [comment]
Possibly, I just triple checked and everything is matching up correctly. Any thoughts on the 404 error? Is that normal?

**Comment by redaxmedia** [comment]
Christopher, the "access forbidden" error you posted comes from the SendGrid API and not from the proxy. This software just adds an Authentication Header, manipulates the CORS header to accept every domain and is passing through the raw traffic.

Please open a ticket on the SendGrid community if you need support.
